# Generated by Django 4.2.1 on 2023-07-02 16:38

import AppMercado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMercado', '0006_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.TextField(max_length=20, primary_key=True, serialize=False, verbose_name=AppMercado.models.Usuario),
        ),
    ]
