# Generated by Django 4.2.1 on 2023-07-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMercado', '0010_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='ventas',
            name='fecha',
            field=models.TextField(default=4.9970017989206476e-05, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
