# Generated by Django 4.2.1 on 2023-07-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMercado', '0011_remove_ventas_id_usuario_ventas_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='fecha',
        ),
    ]
